import { Instrument_Sans, Nunito_Sans } from 'next/font/google';
import './globals.css';
import Header from './home/Header';
import Footer from './home/Footer';

const getInstrumentSans = Instrument_Sans({
	variable: '--font-instrument',
	weights: ['400', '500', '600', '700'],
});

const getNunitoSans = Nunito_Sans({
	variable: '--font-nunito',
	weights: ['400', '600', '700', '800'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${getInstrumentSans.variable} ${getNunitoSans.variable} antialiased`}
			>
				<div>
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
