import { Instrument_Sans, Nunito_Sans } from 'next/font/google';
import './globals.css';
import Header from './Header';
import Footer from './Footer';

const getInstrumentSans = Instrument_Sans({
	variable: '--font-instrument',
	weights: ['400', '500', '600', '700'],
});

const getNunitoSans = Nunito_Sans({
	variable: '--font-nunito',
	weights: ['400', '600', '700', '800'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${getInstrumentSans.variable} ${getNunitoSans.variable} antialiased`}
			>
				<div className="flex flex-col w-full h-full min-h-[100vh] overflow-x-hidden">
					<div className="h-[85px] w-full bg-light-blue sm:bg-white backdrop-blur-md py-4 items-center fixed top-0 z-10 hidden sm:block">
						<Header />
					</div>
					<main className="flex flex-col flex-1 justify-start items-center relative min-h-[50vh] mt-0 sm:mt-[85px]">
						{children}
					</main>
					<div className="py-10 px-4">
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
